default_stages:
  - pre-commit
  - pre-push
fail_fast: true

repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: ruff
        name: Ruff linter
        entry: ruff check
        language: system
        types: [python]

      - id: mypy
        name: mypy type checker
        entry: mypy
        language: system
        types: [python]

      - id: pytest
        name: Run pytest
        entry: pytest
        language: system
        pass_filenames: false
        types: [python]
